export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const ADD_NEW_PROJECT_SUCCESS = "ADD_NEW_PROJECT_SUCCESS";
export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
export const GET_PROFILE = "GET_PROFILE";
export const GET_DETAIL_CAR = "GET_DETAIL_CAR";
export const ADD_NEW_LICENSE_PLATES_SUCCESS = "ADD_NEW_LICENSE_PLATES_SUCCESS";
export const ADD_NEW_LIST_SEAT = "ADD_NEW_LIST_SEAT";
export const ADD_OR_UPDATE_SUCCESS = "ADD_OR_UPDATE_SUCCESS";
export const ADD_MULTI_USER = "ADD_MULTI_USER";
export const GET_USER = "GET_USER";
export const GET_PLATES = "GET_PLATES";
export const SWAP_SEAT_SUCCESS = "SWAP_SEAT_SUCCESS";
export const UPDATE_LICENSE_PLATES_SUCCESS = "UPDATE_LICENSE_PLATES_SUCCESS";
export const DELETE_PLATES_SUCCESS = "DELETE_PLATES_SUCCESS";
export const DELETE_SEAT_SUCCESS = "DELETE_SEAT_SUCCESS";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const SEARCH_PROJECT = "SEARCH_PROJECT";
export const DELETE_LIST_SEAT_SUCCESS = "DELETE_LIST_SEAT_SUCCESS";

export const TITLES = [
  "STT",
  "Người tạo",
  "Ngày khởi hành",
  "Biển số xe ",
  "Hành Động"
];
